**Process Data**

In [2]:
%run Imagenet32_Scripts-master/image_resizer_imagent.py -i ~/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train -o ~/NorthEastern/7374AI/Assignment2/data/resized_train -s 32 -a box -r -j 10

Starting ...
Using algorithm box ...
Recurrent for all folders in in_dir:
 /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01768244
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01443537
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01641577
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01742172
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01644900
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01629819
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01774384
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01770393
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01774750
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n01698640
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imag

/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02132136/images
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02165456/images
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02190166/images
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02206856/images
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02226429
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02226429
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n02226429/images
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03085013
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03179701
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03042490
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03026506
Folder /Users/liulei/NorthEastern/7374AI/Assignmen

Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03838899
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03902125
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03770439
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03796401
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03814639
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03804744
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03837869
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03854065
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03891332
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03930313
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/train/n03838899
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny

In [3]:
%run Imagenet32_Scripts-master/image_resizer_imagent.py -i ~/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/val -o ~/NorthEastern/7374AI/Assignment2/data/resized_val -s 32 -a box

Starting ...
Using algorithm box ...
For folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/val
Folder /Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/val
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/val
/Users/liulei/NorthEastern/7374AI/Assignment2/tiny-imagenet-200/val/images
Finished.


In [4]:
%run Imagenet32_Scripts-master/image2numpy_imagenet_train.py -i ~/NorthEastern/7374AI/Assignment2/data/resized_train -o ~/NorthEastern/7374AI/Assignment2/data/out_data_train

Start program ...
Processing folder /Users/liulei/NorthEastern/7374AI/Assignment2/data/resized_train/box
Processing images from folder n01443537 as label 1


/Users/liulei/NorthEastern/7374AI/Assignment2/Imagenet32_Scripts-master/image2numpy_imagenet_train.py:39: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  img = misc.imread(os.path.join(in_dir, folder, image_name))


Label: 1: n01443537 has 500 samples
Processing images from folder n01629819 as label 2
Label: 2: n01629819 has 500 samples
Processing images from folder n01641577 as label 3
Label: 3: n01641577 has 500 samples
Processing images from folder n01644900 as label 4
Label: 4: n01644900 has 500 samples
Processing images from folder n01698640 as label 5
Label: 5: n01698640 has 500 samples
Processing images from folder n01742172 as label 6
Label: 6: n01742172 has 500 samples
Processing images from folder n01768244 as label 7
Label: 7: n01768244 has 500 samples
Processing images from folder n01770393 as label 8
Label: 8: n01770393 has 500 samples
Processing images from folder n01774384 as label 9
Label: 9: n01774384 has 500 samples
Processing images from folder n01774750 as label 10
Label: 10: n01774750 has 500 samples
Processing images from folder n01784675 as label 11
Label: 11: n01784675 has 500 samples
Processing images from folder n01855672 as label 12
Label: 12: n01855672 has 500 samples
P

Label: 96: n03126707 has 500 samples
Processing images from folder n03160309 as label 97
Label: 97: n03160309 has 500 samples
Processing images from folder n03179701 as label 98
Label: 98: n03179701 has 500 samples
Processing images from folder n03201208 as label 99
Label: 99: n03201208 has 500 samples
Processing images from folder n03250847 as label 100
Label: 100: n03250847 has 500 samples
Processing images from folder n03255030 as label 101
Label: 101: n03255030 has 500 samples
Processing images from folder n03355925 as label 102
Label: 102: n03355925 has 500 samples
Processing images from folder n03388043 as label 103
Label: 103: n03388043 has 500 samples
Processing images from folder n03393912 as label 104
Label: 104: n03393912 has 500 samples
Processing images from folder n03400231 as label 105
Label: 105: n03400231 has 500 samples
Processing images from folder n03404251 as label 106
Label: 106: n03404251 has 500 samples
Processing images from folder n03424325 as label 107
Label:

Label: 188: n07749582 has 500 samples
Processing images from folder n07753592 as label 189
Label: 189: n07753592 has 500 samples
Processing images from folder n07768694 as label 190
Label: 190: n07768694 has 500 samples
Processing images from folder n07871810 as label 191
Label: 191: n07871810 has 500 samples
Processing images from folder n07873807 as label 192
Label: 192: n07873807 has 500 samples
Processing images from folder n07875152 as label 193
Label: 193: n07875152 has 500 samples
Processing images from folder n07920052 as label 194
Label: 194: n07920052 has 500 samples
Processing images from folder n09193705 as label 195
Label: 195: n09193705 has 500 samples
Processing images from folder n09246464 as label 196
Label: 196: n09246464 has 500 samples
Processing images from folder n09256479 as label 197
Label: 197: n09256479 has 500 samples
Processing images from folder n09332890 as label 198
Label: 198: n09332890 has 500 samples
Processing images from folder n09428293 as label 199

In [5]:
%run Imagenet32_Scripts-master/image2numpy_imagenet_val.py -i ~/NorthEastern/7374AI/Assignment2/data/resized_val -o ~/NorthEastern/7374AI/Assignment2/data/out_data_val

Start program ...
Processing folder /Users/liulei/NorthEastern/7374AI/Assignment2/data/resized_val


/Users/liulei/NorthEastern/7374AI/Assignment2/Imagenet32_Scripts-master/image2numpy_imagenet_val.py:49: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  img = misc.imread(os.path.join(in_dir, image_name))


0 : 13
1 : 12
2 : 13
3 : 8
4 : 11
5 : 14
6 : 9
7 : 10
8 : 10
9 : 17
10 : 12
11 : 8
12 : 11
13 : 9
14 : 9
15 : 14
16 : 12
17 : 11
18 : 12
19 : 10
20 : 6
21 : 9
22 : 8
23 : 11
24 : 8
25 : 12
26 : 8
27 : 5
28 : 12
29 : 6
30 : 15
31 : 10
32 : 6
33 : 10
34 : 9
35 : 10
36 : 11
37 : 6
38 : 9
39 : 7
40 : 10
41 : 9
42 : 10
43 : 15
44 : 13
45 : 12
46 : 10
47 : 9
48 : 11
49 : 10
50 : 4
51 : 11
52 : 11
53 : 9
54 : 8
55 : 16
56 : 11
57 : 8
58 : 9
59 : 10
60 : 6
61 : 12
62 : 10
63 : 2
64 : 12
65 : 13
66 : 6
67 : 12
68 : 14
69 : 9
70 : 6
71 : 10
72 : 19
73 : 8
74 : 7
75 : 6
76 : 9
77 : 10
78 : 13
79 : 10
80 : 7
81 : 11
82 : 9
83 : 8
84 : 9
85 : 10
86 : 9
87 : 14
88 : 10
89 : 6
90 : 9
91 : 8
92 : 8
93 : 14
94 : 7
95 : 12
96 : 12
97 : 9
98 : 10
99 : 9
100 : 12
101 : 12
102 : 7
103 : 13
104 : 12
105 : 10
106 : 9
107 : 10
108 : 10
109 : 8
110 : 5
111 : 8
112 : 12
113 : 10
114 : 10
115 : 13
116 : 13
117 : 9
118 : 13
119 : 10
120 : 8
121 : 10
122 : 11
123 : 7
124 : 11
125 : 6
126 : 12
127 : 12
128 : 9
129 

In [6]:
%run Imagenet32_Scripts-master/image2numpy_imagenet_train.py -i ~/NorthEastern/7374AI/Assignment2/data/resized_train_1 -o ~/NorthEastern/7374AI/Assignment2/data/out_data_train_1

Start program ...
Processing folder /Users/liulei/NorthEastern/7374AI/Assignment2/data/resized_train_1/box
Processing images from folder n01443537 as label 1


/Users/liulei/NorthEastern/7374AI/Assignment2/Imagenet32_Scripts-master/image2numpy_imagenet_train.py:39: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  img = misc.imread(os.path.join(in_dir, folder, image_name))


Label: 1: n01443537 has 500 samples
Processing images from folder n01629819 as label 2
Label: 2: n01629819 has 500 samples
Processing images from folder n01641577 as label 3
Label: 3: n01641577 has 500 samples
Processing images from folder n01644900 as label 4
Label: 4: n01644900 has 500 samples
Processing images from folder n01698640 as label 5
Label: 5: n01698640 has 500 samples
Processing images from folder n01742172 as label 6
Label: 6: n01742172 has 500 samples
Processing images from folder n01768244 as label 7
Label: 7: n01768244 has 500 samples
Processing images from folder n01770393 as label 8
Label: 8: n01770393 has 500 samples
Processing images from folder n01774384 as label 9
Label: 9: n01774384 has 500 samples
Processing images from folder n01774750 as label 10
Label: 10: n01774750 has 500 samples
Processing images from folder n01784675 as label 11
Label: 11: n01784675 has 500 samples
Processing images from folder n01855672 as label 12
Label: 12: n01855672 has 500 samples
P

Label: 94: n03089624 has 500 samples
Processing images from folder n03100240 as label 95
Label: 95: n03100240 has 500 samples
Processing images from folder n03126707 as label 96
Label: 96: n03126707 has 500 samples
Processing images from folder n03160309 as label 97
Label: 97: n03160309 has 500 samples
Processing images from folder n03179701 as label 98
Label: 98: n03179701 has 500 samples
Processing images from folder n03201208 as label 99
Label: 99: n03201208 has 500 samples
Processing images from folder n03250847 as label 100
Label: 100: n03250847 has 500 samples
Processing images from folder n03255030 as label 101
Label: 101: n03255030 has 500 samples
Processing images from folder n03355925 as label 102
Label: 102: n03355925 has 500 samples
Processing images from folder n03388043 as label 103
Label: 103: n03388043 has 500 samples
Processing images from folder n03393912 as label 104
Label: 104: n03393912 has 500 samples
Processing images from folder n03400231 as label 105
Label: 105

Label: 185: n07720875 has 500 samples
Processing images from folder n07734744 as label 186
Label: 186: n07734744 has 500 samples
Processing images from folder n07747607 as label 187
Label: 187: n07747607 has 500 samples
Processing images from folder n07749582 as label 188
Label: 188: n07749582 has 500 samples
Processing images from folder n07753592 as label 189
Label: 189: n07753592 has 500 samples
Processing images from folder n07768694 as label 190
Label: 190: n07768694 has 500 samples
Processing images from folder n07871810 as label 191
Label: 191: n07871810 has 500 samples
Processing images from folder n07873807 as label 192
Label: 192: n07873807 has 500 samples
Processing images from folder n07875152 as label 193
Label: 193: n07875152 has 500 samples
Processing images from folder n07920052 as label 194
Label: 194: n07920052 has 500 samples
Processing images from folder n09193705 as label 195
Label: 195: n09193705 has 500 samples
Processing images from folder n09246464 as label 196

In [7]:
%run Imagenet32_Scripts-master/image2numpy_imagenet_val.py -i ~/NorthEastern/7374AI/Assignment2/data/resized_val_1 -o ~/NorthEastern/7374AI/Assignment2/data/out_data_val_1

Start program ...
Processing folder /Users/liulei/NorthEastern/7374AI/Assignment2/data/resized_val_1


/Users/liulei/NorthEastern/7374AI/Assignment2/Imagenet32_Scripts-master/image2numpy_imagenet_val.py:49: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  img = misc.imread(os.path.join(in_dir, image_name))


0 : 13
1 : 12
2 : 13
3 : 8
4 : 11
5 : 14
6 : 9
7 : 10
8 : 10
9 : 17
10 : 12
11 : 8
12 : 11
13 : 9
14 : 9
15 : 14
16 : 12
17 : 11
18 : 12
19 : 10
20 : 6
21 : 9
22 : 8
23 : 11
24 : 8
25 : 12
26 : 8
27 : 5
28 : 12
29 : 6
30 : 15
31 : 10
32 : 6
33 : 10
34 : 9
35 : 10
36 : 11
37 : 6
38 : 9
39 : 7
40 : 10
41 : 9
42 : 10
43 : 15
44 : 13
45 : 12
46 : 10
47 : 9
48 : 11
49 : 10
50 : 4
51 : 11
52 : 11
53 : 9
54 : 8
55 : 16
56 : 11
57 : 8
58 : 9
59 : 10
60 : 6
61 : 12
62 : 10
63 : 2
64 : 12
65 : 13
66 : 6
67 : 12
68 : 14
69 : 9
70 : 6
71 : 10
72 : 19
73 : 8
74 : 7
75 : 6
76 : 9
77 : 10
78 : 13
79 : 10
80 : 7
81 : 11
82 : 9
83 : 8
84 : 9
85 : 10
86 : 9
87 : 14
88 : 10
89 : 6
90 : 9
91 : 8
92 : 8
93 : 14
94 : 7
95 : 12
96 : 12
97 : 9
98 : 10
99 : 9
100 : 12
101 : 12
102 : 7
103 : 13
104 : 12
105 : 10
106 : 9
107 : 10
108 : 10
109 : 8
110 : 5
111 : 8
112 : 12
113 : 10
114 : 10
115 : 13
116 : 13
117 : 9
118 : 13
119 : 10
120 : 8
121 : 10
122 : 11
123 : 7
124 : 11
125 : 6
126 : 12
127 : 12
128 : 9
129 

**Load Data**

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [9]:
def unpickle(file):
    """load the cifar-10 data"""

    with open(file, 'rb') as fo:
        data = pickle.load(fo, encoding='bytes')
    return data

In [30]:
def load_data(data_dir, negatives=False):
    """
    Return train_data, train_labels, test_data, test_labels
    """

    # training data
    train_data = None
    train_labels = []

    # train_data_dict

    for i in range(1, 11):
        train_data_dict = unpickle(data_dir + "/train_data_batch_{}".format(i))
        if i == 1:
            train_data = train_data_dict['data']
        else:
            train_data = np.vstack((train_data, train_data_dict['data']))
#         train_filenames += train_data_dict[b'filenames']
        train_labels += train_data_dict['labels']

    train_data = train_data.reshape((len(train_data), 3, 32, 32))
    print(len(train_data))
    if negatives:
        train_data = cifar_train_data.transpose(0, 2, 3, 1).astype(np.float32)
    else:
        train_data = np.rollaxis(train_data, 1, 4)
#     train_filenames = np.array(train_filenames)
    train_labels = np.array(train_labels)

    # test data
    # cifar_test_data_dict
    # 'batch_label': 'testing batch 1 of 1'
    # 'data': ndarray
    # 'labels': list

    test_data_dict = unpickle(data_dir + "/val_data")
    test_data = test_data_dict['data']
    test_labels = test_data_dict['labels']

    test_data = test_data.reshape((len(test_data), 3, 32, 32))
    if negatives:
        test_data = test_data.transpose(0, 2, 3, 1).astype(np.float32)
    else:
        test_data = np.rollaxis(test_data, 1, 4)
    test_labels = np.array(test_labels)

    return train_data, train_labels, \
           test_data, test_labels

In [84]:
x_train, y_train, x_test, y_test = \
        load_data('data/out_data_train')

100000


In [75]:
x_train_1, y_train_1, x_test_1, y_test_1 = \
        load_data('data/out_data_train_1')

100000


In [76]:
# Original Dataset
x_train_2, y_train_2, x_test_2, y_test_2= \
        load_data('Imagenet32_train')

1281167


In [85]:
y_train.shape

(100000,)

In [87]:
y_train

array([138,  36,  35, ...,  73,  72, 164])

In [88]:
y_train.shape

(100000,)

In [86]:
y_train_2

array([993, 550, 352, ..., 763,  86, 989])

In [89]:
y_train_2.shape

(1281167,)

In [92]:
x_train_ = x_train.astype('float32')
x_test_ = x_test.astype('float32')
x_train_ /= 255
x_test_ /= 255
y_train_ = keras.utils.to_categorical(y_train, 201)
y_test_ = keras.utils.to_categorical(y_test, 201)

In [94]:
y_train

array([138,  36,  35, ...,  73,  72, 164])

In [93]:
y_train_

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [95]:
x_train_22 = x_train_2.astype('float32')
x_test_22 = x_test_2.astype('float32')
x_train_22 /= 255
x_test_22 /= 255
y_train_22 = keras.utils.to_categorical(y_train_2, 1001)
y_test_22 = keras.utils.to_categorical(y_test_2, 1001)

In [96]:
y_train_22

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [100]:
y_test_2[1]

814

In [ ]:
for i in range(0,1281166):
    if y_test_2[i] ==

**Experiment 1 - CNN Model**

In [45]:
from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import os
from keras import metrics

/anaconda3/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [42]:
save_dir = os.path.join(os.getcwd(), 'saved_models')
model_name = 'keras_Imagenet32_trained_model.h5'

In [54]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 200)
y_test = keras.utils.to_categorical(y_test, 200)

In [55]:
datagen = ImageDataGenerator(
    featurewise_center=False,  # set input mean to 0 over the dataset
    samplewise_center=False,  # set each sample mean to 0
    featurewise_std_normalization=False,  # divide inputs by std of the dataset
    samplewise_std_normalization=False,  # divide each input by its std
    zca_whitening=False,  # apply ZCA whitening
    zca_epsilon=1e-06,  # epsilon for ZCA whitening
    rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
    # randomly shift images horizontally (fraction of total width)
    width_shift_range=0.1,
    # randomly shift images vertically (fraction of total height)
    height_shift_range=0.1,
    shear_range=0.,  # set range for random shear
    zoom_range=0.,  # set range for random zoom
    channel_shift_range=0.,  # set range for random channel shifts
    # set mode for filling points outside the input boundaries
    fill_mode='nearest',
    cval=0.,  # value used for fill_mode = "constant"
    horizontal_flip=True,  # randomly flip images
    vertical_flip=False,  # randomly flip images
    # set rescaling factor (applied before any other transformation)
    rescale=None,
    # set function that will be applied on each input
    preprocessing_function=None,
    # image data format, either "channels_first" or "channels_last"
    data_format=None,
    # fraction of images reserved for validation (strictly between 0 and 1)
    validation_split=0.0)
    
# Compute quantities required for feature-wise normalization
# (std, mean, and principal components if ZCA whitening is applied).
datagen.fit(x_train)

In [56]:
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same',
input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [59]:
model.compile(loss='categorical_crossentropy',
optimizer=keras.optimizers.rmsprop(lr=0.0002, decay=1e-6),
metrics=['accuracy',metrics.categorical_accuracy])

model.fit_generator(datagen.flow(x_train, y_train,
    batch_size=32),
    epochs=5,
    steps_per_epoch=2000,
    validation_data=(x_test, y_test),
    workers=4)

Epoch 1/5
 173/2000 [=>............................] - ETA: 3:17 - loss: 5.3033 - acc: 0.0040 - categorical_accuracy: 0.0040

KeyboardInterrupt: 

In [60]:
x_train_2 = x_train_2.astype('float32')
x_test_2 = x_test_2.astype('float32')
x_train_2 /= 255
x_test_2 /= 255
y_train_2 = keras.utils.to_categorical(y_train_2, 1000)
y_test_2 = keras.utils.to_categorical(y_test_2, 1000)

IndexError: index 1000 is out of bounds for axis 1 with size 1000

In [70]:
datagen = ImageDataGenerator(
    featurewise_center=False,  # set input mean to 0 over the dataset
    samplewise_center=False,  # set each sample mean to 0
    featurewise_std_normalization=False,  # divide inputs by std of the dataset
    samplewise_std_normalization=False,  # divide each input by its std
    zca_whitening=False,  # apply ZCA whitening
    zca_epsilon=1e-06,  # epsilon for ZCA whitening
    rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
    # randomly shift images horizontally (fraction of total width)
    width_shift_range=0.1,
    # randomly shift images vertically (fraction of total height)
    height_shift_range=0.1,
    shear_range=0.,  # set range for random shear
    zoom_range=0.,  # set range for random zoom
    channel_shift_range=0.,  # set range for random channel shifts
    # set mode for filling points outside the input boundaries
    fill_mode='nearest',
    cval=0.,  # value used for fill_mode = "constant"
    horizontal_flip=True,  # randomly flip images
    vertical_flip=False,  # randomly flip images
    # set rescaling factor (applied before any other transformation)
    rescale=None,
    # set function that will be applied on each input
    preprocessing_function=None,
    # image data format, either "channels_first" or "channels_last"
    data_format=None,
    # fraction of images reserved for validation (strictly between 0 and 1)
    validation_split=0.0)
    
# Compute quantities required for feature-wise normalization
# (std, mean, and principal components if ZCA whitening is applied).
datagen.fit(x_train_2)

In [71]:
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same',
input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [73]:
model.compile(loss='categorical_crossentropy',
optimizer=keras.optimizers.rmsprop(lr=0.0002, decay=1e-6),
metrics=['accuracy',metrics.categorical_accuracy])

model.fit_generator(datagen.flow(x_train_2, y_train_2,
    batch_size=32),
    epochs=5,
    steps_per_epoch=2000,
    validation_data=(x_test_2, y_test_2),
    workers=4)

ValueError: Error when checking target: expected activation_12 to have shape (201,) but got array with shape (1,)